# Variables
@baseUrl = http://localhost:3333/v1

# Create user
# @name createUser
POST  {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Railson Teste",
  "email": "railson10@teste.com",
  "password": "123123",
  "phone": "85992179885",
  "role": "admin"
}

###